Adding attribution to places where an OpenLayers.Map gets created
jpatokal/openflights pull request #1037
Opened 2020-08-13 14:18 UTC by kmpoppe

Closes #916 .

Hey Jani,

I thought I could just give you a PR for the attribution, no need to make you go the long way round.

Please TRY IT before merging (check out my branch) because due to time issues I couldn't set up everything to try it myself.

HTH.

Kai

2023-03-01 02:07 UTC, reedy commented
For the lazy, how would I test this? Or rather, how/where would the copyright attribution for the map actually appear? :)

2023-03-01 05:28 UTC, kmpoppe commented
Hi there,

you will see the attribution in the lower right-hand corner of the map with the text (© openstreetmap contributors).

I should work worry-free, if you have a local version set up you should easily be able to spot it before publishing it :)

K

2023-03-01 15:32 UTC, reedy commented
<img width="681" alt="Screenshot 2023-03-01 at 15 30 42" src="https://user-images.githubusercontent.com/67615/222185729-f6edcc5d-33f1-47b5-95f9-5d4ecba46133.png">

With your patch cherry-picked onto master, I don't see anything extra on the map in terms of attribution...

2023-04-07 16:05 UTC, reedy requested changes
Doesn't seem to work in my testing, and while the json blob for the attribution looks right, it doesn't look like it's in the right place or under the right object

2023-04-07 16:05 UTC, reedy commented on openflights.js
> +	},
I think, looking at line 134 below, this needs to be under a layer...

See also like https://github.com/openlayers/openlayers/compare/release-2.11...v2.13.1#diff-99e6b60d1f8e64080689545ad1091989875914a0d2b7bde885525413682473beR13-R17

And maybe an attribution control adding?

2023-04-23 15:20 UTC, reedy commented on openflights.js
> +	},
I'm also curious which layer(s) the OSM attribution needs to be against too. Especially as below the "Artistic", "Political" and "Satellite" have attribution...

But I also cannot see where those attributions appear on the maps either.

2023-04-23 15:29 UTC, reedy commented
Finding appropriate documentation is made harder by OpenFlights using a version of OpenLayer from ~November 2011. Seemingly version 2.11. 7.3 is now out.

Ping https://github.com/jpatokal/openflights/issues/1192

2023-04-23 15:32 UTC, reedy commented
https://github.com/openlayers/openlayers/blob/release-2.11/examples/attribution.html would be the relevant docs...

2023-04-23 15:45 UTC, reedy commented on openflights.js
> +	},
Ok, and the key is for those attributions not appearing...

https://github.com/openlayers/openlayers/blob/release-2.11/examples/attribution.html#L31-L34

![Screenshot 2023-04-23 at 16 40 00](https://user-images.githubusercontent.com/67615/233849580-ab7e9ea6-9b3f-4b9f-aa38-b51634abdc25.png)

It's not pretty... But it's a start...

```
diff --git a/openflights.js b/openflights.js
index 8c2db2d..9e43d17 100644
--- a/openflights.js
+++ b/openflights.js
@@ -115,7 +115,8 @@ function init(){
       new OpenLayers.Control.Navigation({'title': gt.gettext("Toggle pan and region select mode")}),
       new OpenLayers.Control.LayerSwitcher({'ascending':false, 'title': gt.gettext('Switch map layers')}),
       new OpenLayers.Control.ScaleLine(),
-      new OpenLayers.Control.OverviewMap({'title': gt.gettext("Toggle overview map")})
+      new OpenLayers.Control.OverviewMap({'title': gt.gettext("Toggle overview map")}),
+      new OpenLayers.Control.Attribution()
     ] });
 
   // Horrible hack to stop OpenLayers 2 from showing ZL < 2
```

Need to play around with the location of things...

2023-04-23 15:59 UTC, reedy commented on openflights.js
> +	},
Which looks to be done in CSS - https://stackoverflow.com/questions/20981679/openlayers-map-change-position-of-attribution-in-javascript

````
.olControlAttribution {
    font-size: smaller; 
    right: 3px; 
    bottom: 4.5em; 
    position: absolute; 
    display: block;
}
```

2023-04-23 16:04 UTC, reedy commented on openflights.js
> +	},
Hmm. And after https://github.com/jpatokal/openflights/commit/a5c352206c7d31fe59ad2349a34c3b4597dd5a15 it seems to be working as expected...

Yeah, the colours suck on some of the maps...

![Screenshot 2023-04-23 at 17 03 33](https://user-images.githubusercontent.com/67615/233850856-f7e54acb-f873-4c63-9764-05ec39cc4502.png)
![Screenshot 2023-04-23 at 17 03 36](https://user-images.githubusercontent.com/67615/233850858-e404f881-af0f-4c96-8905-0ea2439a5530.png)
![Screenshot 2023-04-23 at 17 03 39](https://user-images.githubusercontent.com/67615/233850860-82bcd93d-5105-4d5a-9f2e-9e79a4d9185f.png)

2023-04-23 16:18 UTC, reedy commented
May no longer be needed/superseded by https://github.com/jpatokal/openflights/commit/b82c1443501a7f80eabb0cf356d5402c8b114a39

2023-06-26 11:47 UTC, closed without merging