Addressing PHP 8 warnings
jpatokal/openflights pull request #1207
Opened 2023-06-19 23:31 UTC by chrisrosset

- Added the null coalescing operator (`??`) in tons of places to avoid warnings (notices before version 8) about undefined array keys. The most common use cases are reading optional request parameters or handling multiple different request types in the same place.
- `auto_detect_line_endings` is [deprecated in PHP 8](https://php.watch/versions/8.1/auto_detect_line_endings-ini-deprecated) and redundant.
- MySQL returns `null` for SUM on zero rows. Used `COALESCE` to get 0 instead for use in calculations. (scenario: User settings page for a user without any flights - e.g. a new user)
- Used `intdiv` to avoid "PHP deprecated: Implicit conversion from float ... to int loses precision" when calculation the total flight duration in days/hours/minutes for the banner.
- The `seattype` field is not defined while processing CSV imports. I set the value to `""` to avoid an undefined variable warning when the variable is used to present the user with the data read out of the file. Side note: I don't believe this field is actually used.
- Added `"" => ""` mappings in `import.php`'s' class/reason/pos lookup tables to avoid undefined array key warnings for cases.

2023-06-19 23:32 UTC, chrisrosset commented
Resolves #1154.
Resolves #1155.

2023-06-26 12:23 UTC, reedy commented on php/stats.php
> -// This applies only when viewing another users flights
Guess this comment wasn't removed on purpose (still exists in the top10.php code below)

2023-06-26 12:23 UTC, reedy commented on badge/banner.php
> +        intdiv($row["duration"], 60) % 24,
This looks a bit weird to be (I'd probably be more tempted to use `(int)` casting), but very much a stylistic choice. So doesn't really matter.

I know some IDE's complain about some calls like this for performance reasons, but this doesn't seem to be one of them.

2023-07-08 10:54 UTC, reedy requested changes

2023-07-08 10:54 UTC, reedy commented on php/stats.php
> -// This applies only when viewing another users flights
^

2023-07-08 13:45 UTC, reedy commented on php/top10.php
> +$limit = $_POST["limit"] ?? "10";
These changes upwards conflicted with 282fe65d9481d917f40b95c94cf1fc27c205a409 which did some similar changes

2023-07-08 13:47 UTC, reedy commented
Rebased and amended; pushed as 52e054d87d63ba0d43153ff61ef8ed59b8fb0d3a

2023-07-08 13:47 UTC, closed without merging